#!/bin/bash
#: Title       : setting
#: Date        : 2012-04-24
#: Author      : "Ery Lee" <ery.lee@gmail.com> from opengoss.com
#: Version     : 1.0 
#: Description : mysql, amqp, errdb settings

# Identify the script name
SCRIPT=`basename $0`
ROOTDIR=$(cd ${0%/*} && pwd)
VERSION=1.0
DATE_OF_CREATION=2012-04-26
AUTHOR="Ery Lee <ery.lee@gmail.com>"

#amqp, FIX here
AMQP_HOST=localhost
AMQP_VHOST=wifioss
AMQP_USER=wifioss
AMQP_PASS=public

OS_TYPE=`uname`
if [ "$OS_TYPE" == "Darwin" ]; then
	SED_OPTS="-i ''"
else
	SED_OPTS="-i"
fi

#configure node
cd $ROOTDIR/etc/
echo "configuring etc/trapd.config..."
cp trapd.config.origin trapd.config
sed -e "s/AMQP_HOST/$AMQP_HOST/g" \
	-e "s/AMQP_VHOST/$AMQP_VHOST/g" \
	-e "s/AMQP_USER/$AMQP_USER/g" \
	-e "s/AMQP_PASS/$AMQP_PASS/g" \
	$SED_OPTS trapd.config

